export const GET_USER = "GET_USER"
export const GET_USER_BY_ID = "GET_USER_BY_ID"


export const USER_REGISTER="USER_REGISTER"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL="USER_REGISTER_FAIL"



export const USER_LOGIN="USER_LOGIN"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"


export const GET_PROFILE = "GET_PROFIL";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";



