export const GET_POST = "GET_POST";
export const GET_POST_BY_ID = "GET_POST_BY_ID"


export const POST_REGISTER="POST_REGISTER";
export const POST_REGISTER_SUCCESS="POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAIL="POST_REGISTER_FAIL";




export const DELETE_POST="DELETE_POST";
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL="DELETE_POST_FAIL";